name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: "Type DEPLOY to approve deployment"
        required: true
        default: ""

jobs:
  deploy:
    if: github.event.inputs.deploy == 'DEPLOY'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deployment Approved
        run: echo "Deployment Approved"

      - name: Merge Development into Testing
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git checkout testing
          git merge development

          echo "Merged development into testing"